topics:
 - name: /xbotcore/joint_states
   compress: true
   rate: 50.0 
 - name: /xbotcore/status
   compress: false
   rate: 10.0 
 - name: /xbotcore/statistics
   compress: false
   rate: 10.0 
 - name: /xbotcore/joint_device_info
   compress: false
   rate: 10.0 
 - name: /xbotcore/joint_states
   compress: true
   rate: 50.0 
 - name: /cam_sender/encoded
   compress: false
